update iac pipline

diff --git a/.github/workflows/iac-pipline.yml b/.github/workflows/iac-pipline.yml
--- a/.github/workflows/iac-pipline.yml
+++ b/.github/workflows/iac-pipline.yml
@@ -44,18 +44,20 @@ jobs:
 
       - name: Run Terrascan
         run: |
-          docker run --rm -v $(pwd):/workspace -w /workspace accurics/terrascan scan -t aws -d /terraform
+          pwd
+          docker run --rm -v $(pwd):/workspace -w /workspace accurics/terrascan scan -t aws -d /workspace/terraform
         continue-on-error: true
+        
       - name: Terraform Plan
         id: plan
-        run: terraform plan -no-color -input=false -out planfile
+        run: terraform plan -no-color 
         continue-on-error: true
 
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+      # - name: Terraform Plan Status
+      #   if: steps.plan.outcome == 'failure'
+      #   run: exit 1
 
       - name: Terraform Apply
         id: apply
         if: github.ref == 'refs/heads/master' && github.event_name == 'push'
-        run: terraform apply -auto-approve -input=false -parallelism=1 planfile
+        run: terraform apply -auto-approve 
